language: python
sudo: false
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$PYTHON_VERSION pip numpy scipy nose flake8 h5py
  - source activate env_name
  - conda install --yes -c https://conda.anaconda.org/biocore VSEARCH MAFFT SortMeRNA
  - pip install coveralls
  - travis_retry pip install .
before_script:
  - export MOI_CONFIG_FP=$HOME/miniconda3/envs/qiita_env/lib/python2.7/site-packages/qiita_core/support_files/config_test.cfg
  - qiita pet webserver start &
script:
  - sleep 10 # give enough time to the webserver to start
  - configure_deblur --env-script "source activate qp-deblur" --server-cert $QIITA_SERVER_CERT
  - nosetests --with-doctest --with-coverage
  - flake8 qp_deblur setup.py scripts
addons:
  postgresql: "9.3"
services:
  - redis-server
  - postgresql
after_success:
  - coveralls
